### ISSUE TITLE
Category index pages not appearing for all categories

### ISSUE THREAD

**Issue by matthewl** [octopress/category-index#6]
I'm writing this up as an issue, but it could be me being dumb.

I've just about migrated my blog over from Octopress 2 to Octopress 3. Everything is built as expected but I'm having an issue with the category-index gem. After my site has been generated I find a `category_index.html` file sitting in the root of my `_site` folder with only the first category in it.

I've added the gem, bundle installed, added the gem to the `_config.yml` file and added a `config.yml` file in `/_plugins/categories/`. Next, in the categories plugin config file, I've listed a number of categories I want to generate category pages for:

```
categories:
 - Daily Post
 - Link Love
 - Monthly Redux
```

My understanding is that the gem will use these categories to generate category pages, but I'm not seeing category pages for all of these. Instead I'm seeing the `category_index.html` being generated in the root of the `_site` folder with only the first category in it.

**Comment by imathis** [comment]
I'm sorry If I've wasted your time. I need to take this down. [Here's why](https://github.com/octopress/category-index/issues/2#issuecomment-77193081).

**Comment by imathis** [comment]
I plan to release a similar plugin that will use templates from your site source instead of asking you to override these. I just haven't had time to work on it yet.

**Comment by matthewl** [comment]
No worries. I seen the comment a few minutes after I posted this but I figured I would leave it up anyway in case anything had changed.
